replicaCount: 3

image:
  repository: sarahasadi/devops-fastapi
  tag: 0.1.2
  pullPolicy: IfNotPresent

containerPort: 8000

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

livenessProbe:
  path: /healthz
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  path: /readyz
  initialDelaySeconds: 5
  periodSeconds: 5
