replicaCount: 1

image:
  repository: sarahasadi/devops-fastapi
  tag: "2652973f84b0e176e9eb38415a74e73b08aeafe2"
  pullPolicy: IfNotPresent

containerPort: 8000

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

config:
  APP_NAME: "fastapi-devops-sample"
  APP_ENV: "development"
  LOG_LEVEL: "debug"

ingress:
  enabled: true
  host: fastapi-dev.local

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
