apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fastapi.fullname" . }}
  labels:
    app: {{ include "fastapi.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ include "fastapi.name" . }}

  template:
    metadata:
      labels:
        app: {{ include "fastapi.name" . }}

    spec:
      containers:
        - name: fastapi
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          envFrom:
            - configMapRef:
                name: {{ include "fastapi.fullname" . }}-config

          ports:
            - containerPort: {{ .Values.containerPort }}

          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 5

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
